"""AI Chef Lambda handler.

Supports two modes:
1. /chef - Invoke Bedrock model with optional guardrail (guardrail=true/false)
2. /check-guardrail - Standalone ApplyGuardrail to validate text without model invocation

Models supported:
- us.amazon.nova-2-lite-v1:0 (default, no model access request needed)
- anthropic.claude-3-5-haiku-20241022-v1:0 (requires model access in Bedrock console)
"""

import json
import logging
import os
from typing import Any

import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

bedrock_runtime = boto3.client("bedrock-runtime")

GUARDRAIL_ID: str = os.environ["GUARDRAIL_ID"]
GUARDRAIL_VERSION: str = os.environ["GUARDRAIL_VERSION"]
MODEL_ID: str = os.environ.get("MODEL_ID", "us.amazon.nova-2-lite-v1:0")

CHEF_SYSTEM_PROMPT: str = (
    "You are a professional chef assistant. You ONLY answer questions about cooking, "
    "recipes, culinary techniques, ingredients, kitchen equipment, and food preparation. "
    "Always respond in the same language the user writes in. "
    "If asked about anything unrelated to cooking, politely redirect to culinary topics."
)


def lambda_handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Route requests based on the API Gateway resource path."""
    logger.info(json.dumps({"event": event}, default=str))

    path: str = event.get("resource", "")

    try:
        body = json.loads(event.get("body", "{}"))
    except (json.JSONDecodeError, TypeError):
        return _response(400, {"error": "Invalid JSON in request body"})

    try:
        if path == "/check-guardrail":
            return _handle_guardrail_check(body)
        return _handle_chef_request(body)
    except Exception:
        logger.exception("Unhandled error")
        return _response(500, {"error": "Internal server error"})


def _handle_chef_request(body: dict[str, Any]) -> dict[str, Any]:
    """Invoke Bedrock model with or without guardrail based on request parameter."""
    message: str = body.get("message", "")
    use_guardrail: bool = body.get("guardrail", True)

    if not message:
        return _response(400, {"error": "Field 'message' is required"})

    converse_params: dict[str, Any] = {
        "modelId": MODEL_ID,
        "system": [{"text": CHEF_SYSTEM_PROMPT}],
        "messages": [
            {
                "role": "user",
                "content": [{"text": message}],
            }
        ],
        "inferenceConfig": {
            "maxTokens": 4096,
            "temperature": 0.3,
        },
    }

    if use_guardrail:
        converse_params["guardrailConfig"] = {
            "guardrailIdentifier": GUARDRAIL_ID,
            "guardrailVersion": GUARDRAIL_VERSION,
        }

    response = bedrock_runtime.converse(**converse_params)

    output_text: str = response["output"]["message"]["content"][0]["text"]
    stop_reason: str = response.get("stopReason", "unknown")

    result: dict[str, Any] = {
        "response": output_text,
        "guardrail_enabled": use_guardrail,
        "stop_reason": stop_reason,
        "model_id": MODEL_ID,
    }

    # Include guardrail trace if intervention occurred
    if stop_reason == "guardrail_intervened":
        result["guardrail_action"] = "BLOCKED"
        trace = response.get("trace", {}).get("guardrail", {})
        if trace:
            result["guardrail_trace"] = _extract_trace_summary(trace)

    return _response(200, result)


def _handle_guardrail_check(body: dict[str, Any]) -> dict[str, Any]:
    """Standalone ApplyGuardrail - validate text without invoking a model.

    This is useful for:
    - Pre-validating user input before sending to the model (saves cost)
    - Validating content generated by other sources
    - Building content moderation pipelines
    """
    text: str = body.get("text", "")
    source: str = body.get("source", "INPUT")

    if not text:
        return _response(400, {"error": "Field 'text' is required"})

    if source not in ("INPUT", "OUTPUT"):
        return _response(400, {"error": "Field 'source' must be 'INPUT' or 'OUTPUT'"})

    # ApplyGuardrail API - content format: [{"text": {"text": "..."}}]
    response = bedrock_runtime.apply_guardrail(
        guardrailIdentifier=GUARDRAIL_ID,
        guardrailVersion=GUARDRAIL_VERSION,
        source=source,
        content=[{"text": {"text": text}}],
    )

    action: str = response.get("action", "NONE")
    assessments: list = response.get("assessments", [])

    result: dict[str, Any] = {
        "action": action,
        "text_analyzed": text,
        "source": source,
    }

    if action == "GUARDRAIL_INTERVENED":
        result["outputs"] = [o.get("text", "") for o in response.get("outputs", [])]

    if assessments:
        result["assessments"] = _format_assessments(assessments)

    return _response(200, result)


def _extract_trace_summary(trace: dict[str, Any]) -> dict[str, Any]:
    """Extract a readable summary from the guardrail trace."""
    summary: dict[str, Any] = {}

    if "inputAssessment" in trace:
        summary["input"] = _format_single_assessment(trace["inputAssessment"])

    if "outputAssessments" in trace:
        output_assessments = trace["outputAssessments"]
        if output_assessments:
            summary["output"] = _format_single_assessment(output_assessments[0])

    return summary


def _format_assessments(assessments: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Format assessment list from ApplyGuardrail response."""
    return [_format_single_assessment(a) for a in assessments]


def _format_single_assessment(assessment: dict[str, Any]) -> dict[str, Any]:
    """Format a single assessment into a readable dict."""
    result: dict[str, Any] = {}

    topic_policy = assessment.get("topicPolicy", {})
    if topic_policy.get("topics"):
        result["topics_detected"] = [
            {"name": t.get("name"), "action": t.get("action")}
            for t in topic_policy["topics"]
        ]

    content_policy = assessment.get("contentPolicy", {})
    if content_policy.get("filters"):
        result["content_filters"] = [
            {
                "type": f.get("type"),
                "confidence": f.get("confidence"),
                "action": f.get("action"),
            }
            for f in content_policy["filters"]
        ]

    word_policy = assessment.get("wordPolicy", {})
    managed = word_policy.get("managedWordLists", [])
    custom = word_policy.get("customWords", [])
    if managed or custom:
        result["word_filters"] = {
            "managed_words": [
                {"match": w.get("match"), "type": w.get("type")} for w in managed
            ],
            "custom_words": [
                {"match": w.get("match"), "action": w.get("action")} for w in custom
            ],
        }

    sensitive_policy = assessment.get("sensitiveInformationPolicy", {})
    pii = sensitive_policy.get("piiEntities", [])
    regexes = sensitive_policy.get("regexes", [])
    if pii or regexes:
        result["sensitive_info"] = {
            "pii_entities": [
                {
                    "type": p.get("type"),
                    "action": p.get("action"),
                    "match": p.get("match"),
                }
                for p in pii
            ],
            "regex_matches": [
                {
                    "name": r.get("name"),
                    "action": r.get("action"),
                    "match": r.get("match"),
                }
                for r in regexes
            ],
        }

    return result


def _response(status_code: int, body: dict[str, Any]) -> dict[str, Any]:
    """Build API Gateway proxy response with CORS headers."""
    return {
        "statusCode": status_code,
        "headers": {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
        },
        "body": json.dumps(body, ensure_ascii=False, default=str),
    }
